### ISSUE TITLE
depends 'news' => '3.2.5-4.9.99'

### ISSUE THREAD

**Issue by metiny** [georgringer/news_feuser#4]
Hi Georg,
thank you for your great work again!

i installed it on 7.6.11 with news 5.10
in EM: The extension news is installed in version 5.1.0 but needed in version 3.2.5 - 4.9.99

depends 'news' => '3.2.5-4.9.99'

**Comment by georgringer** [comment]
released 2.0.0 which works with 8.7+, so I am closing this
