### ISSUE TITLE
ext: news_feuser for TYPO3 9.x.x will be?

### ISSUE THREAD

**Issue by typo3ua** [georgringer/news_feuser#5]
When will be ext: news_feuser for TYPO3 9.x.x ?

**Comment by georgringer** [comment]
Wanna sponsor it?

**Comment by typo3ua** [comment]
Nope! Because I do it free for Ukrainian TYPO3 community - dev.typo3.org.ua

**Comment by georgringer** [comment]
released 2.0.0, should work out fine

**Comment by typo3ua** [comment]
Thanks a lot!
