### ISSUE TITLE
News of user - No news available

### ISSUE THREAD

**Issue by typo3ua** [georgringer/news_feuser#6]
I can not display the news items which belong to a given frontend user, which is logged and has current status "Login successful"

That is what I did on this moment:

1. Installed ext: news
2. Installed ext: news_feuser
3. Added few "News item"
4. Added few "Frontend user"
5. Tied different "Frontend user" to different "News items"
6. Added Plugin on the page.
7. Chosed in the "What to display" - "News of user"
8. Did duplicate the template file List.html with the name PerUser.html 

In the final result I see on the page "No news available"

What is wrong I did or what do not yet?

**Comment by georgringer** [comment]
check out the extension manager settings (in 9 in install tool) and define something like "user". this will be the GET variable name used to fetch the user's records. then go the list view and build a link, like `<f:link.page additionalParams="{user:1}">link to all news of user with id 1</f:link.page>

**Comment by typo3ua** [comment]
Georg, thanks a lot! It is working.
